t-sweets/pos

app/controllers/api/products_controller.rb
app/models/purchase.rb
config/routes.rb

* endpoint: `base_url/api/v1/products/:id`
* method: DELETE
* authorization: `admin`, `pos`, `arriver`
* success
```json
{
"success": true,
"product": {
"id": 3,
"name": "餃子",
"price": 130,
"image_path": "gyouza.png",
"cost": 100,
"stock": 10,
"notification": true,
"notification_stock": 3,
"display": true,
"created_at": "2019-02-12T14:48:01.000Z",
"updated_at": "2019-02-12T14:48:01.000Z"
}
}
```
* failure
```json
{
"success": false,
"errors":[
{
"base":[
"Cannot delete record because dependent purchase items exist"
]
}
]
}
```

add product delete

---

app/controllers/api/users_controller.rb
config/routes.rb

* endpoint: `base_url/api/v1/users`
* method: GET
* authorization: `admin`
```json
[
{
"id": 1,
"name": "sharikae",
"email": "sharikae@example.com",
"authority_id": 1,
"created_at": "2019-02-12T15:00:29.000Z"
},
{
"id": 2,
"name": "yamashita",
"email": "sho@example.com",
"authority_id": 2,
"created_at": "2019-02-12T15:00:29.000Z"
},
{
"id": 3,
"name": "ishiguro",
"email": "ishiguro@example.com",
"authority_id": 3,
"created_at": "2019-02-12T15:00:30.000Z"
}
]
```

add user index

---

app/controllers/api/auth/registrations_controller.rb

fix user-update

---

app/controllers/api/products_controller.rb
app/models/product.rb
config/routes.rb

* endpoint: `base_url/api/v1/products/:id/stock`
* method: POST
* authorization: `admin`, `arriver`
* request body sample:
```json
{
"additional_quantity": 10
}
```
* success
```json
{
"success": true,
"product": {
"stock": 13,
"id": 2,
"name": "アイス",
"price": 100,
"image_path": "https://2.bp.blogspot.com/-t7fJ99VE-HY/W64DlIeosgI/AAAAAAABPH8/fzyUKstvUT0mu7Aqt1em7Lms0ttprj_tQCLcBGAs/s800/icecream_cup_spoon_wood.png",
"display": true,
"notification": false,
"cost": null,
"notification_stock": null,
"created_at": "2019-02-16T06:09:06.000Z",
"updated_at": "2019-02-16T06:57:26.000Z"
}
}
```
* failure
```json
{
"success": false,
"product":[
"you cannot reduce stock with your authority."
]
}
```
* endpoint: `base_url/api/v1/products/:id/price/`
* method: POST
* …

add_stock and increase_price method added

---

app/controllers/api/auth/registrations_controller.rb

fix incorrect property name

---

app/controllers/api/products_controller.rb
app/controllers/api/purchases_controller.rb
app/controllers/application_controller.rb

unitify response status code

---

app/controllers/api/auth/registrations_controller.rb
app/controllers/api/products_controller.rb
app/controllers/api/purchases_controller.rb
app/controllers/api/users_controller.rb
app/controllers/application_controller.rb
app/models/purchase.rb
app/models/purchase_item.rb
config/routes.rb

|:---:|---|
|DELETE|`base_url/api/v1/purchases/:id`|
|○|○|×|×|
```json
{
"success": true,
"purchase": {
"id": 1,
"payment_method_id": 2,
"payment_uuid": "3l40g9fg493",
"created_at": "2019-02-21T15:22:16.000Z",
"updated_at": "2019-02-21T15:22:16.000Z"
}
}
```

add purchase cancel

---

app/controllers/api/audit_logs_controller.rb
config/routes.rb

|:---:|---|
|POST|`base_url/api/v1/audit_logs`|
|○|×|×|×|
```json
[
{
"id": 1,
"model": "product",
"model_id": 1,
"operation": "create",
"operator": 1,
"detail": "this model created by seeder.",
"created_at": "2019-02-23T12:07:47.000Z",
"updated_at": "2019-02-23T12:07:47.000Z"
},
{
"id": 2,
"model": "purchase",
"model_id": 1,
"operation": "create",
"operator": 2,
"detail": "this model created by seeder.",
"created_at": "2019-02-23T12:07:47.000Z",
"updated_at": "2019-02-23T12:07:47.000Z"
},
{
"id": 3,
"model": "user",
"model_id": 2,
"operation": "create",
"operator": 1,
"detail": "this model created by seeder.",
"created_at": "2019-02-23T12:07:47.000Z",
"updated_at": …
```

add audit logs index

---

app/controllers/api/purchases_controller.rb
app/models/purchase.rb
app/models/purchase_item.rb

add method for slack receipt

---

app/controllers/api/withdraws_controller.rb
app/models/balance.rb
app/models/withdraw.rb
config/routes.rb
db/migrate/20190226102945_create_withdraw.rb
db/schema.rb
db/seeds.rb

|:---:|---|
|POST|`base_url/api/v1/withdraws`|
|○|×|○|×|
* request body sample:
```json
{
"amount": 2000
}
```
```json
{
"id": 2,
"amount": 2600,
"sales": 300,
"card_added": 3000,
"created_at": "2019-02-26T10:55:22.000Z",
"updated_at": "2019-02-26T10:55:22.000Z"
}
```

add withdraw

---

app/models/purchase.rb

add subtotal

---

app/controllers/api/auth/registrations_controller.rb
app/controllers/api/auth/sessions_controller.rb
config/routes.rb

fix #48
```json
{
"name": "sharikae",
"password": "3lkh4jg0dfkj345hl23"
}
```

sign in with ldap name

---

app/controllers/api/auth/registrations_controller.rb

fix signup

---

app/controllers/api/products_controller.rb

fix product destroy

---

Dockerfile
app/controllers/api/purchases_controller.rb
config/application.rb

使えるパラメタ
* year
* month
* product_id

salesのエンドポイントにパラメタ追加

---

app/controllers/api/products_controller.rb
config/routes.rb
db/migrate/20190122151510_create_products.rb
db/schema.rb
db/seeds.rb

|:---:|---|
|GET|`base_url/api/v1/products/jan/:code`|
|○|○|×|×|
```json
{
"id": 1,
"name": "カップラーメン",
"price": 130,
"image_uuid": "eba953f6-decf-453b-b6ec-fb2c283fc851",
"image_path": "/product_images/2819b019-46e8-4f1d-9f83-4d248faf066f.png",
"cost": null,
"stock": 5,
"notification": true,
"notification_stock": 3,
"display": true,
"jan": "23045630",
"created_at": "2019-03-26T18:14:48.000+09:00",
"updated_at": "2019-03-26T18:14:48.000+09:00"
}
```

add method to search by jan code

---

app/controllers/api/products_controller.rb
config/routes.rb
db/seeds.rb

|:---:|---|
|GET|`base_url/api/v1/products/active`|
|○|○|○|○|
```json
[
{
"id": 1,
"name": "カップラーメン",
"price": 130,
"image_path": "/product_images/94f5f6df-2ae9-496c-ac7d-18a9f267fd09.png",
"cost": null,
"stock": 5,
"display": true,
"created_at": "2019-01-25T16:59:24.000Z",
"updated_at": "2019-01-25T16:59:24.000Z"
}
```

add endpoint acrive_all

---

app/controllers/api/deposits_controller.rb
app/controllers/api/registers_controller.rb
app/controllers/api/withdraws_controller.rb

|:---:|---|
|POST|`base_url/api/v1/withdraws`|
|○|×|○|×|
* request body sample:
```json
{
"amount": 2000,
"detail": "for arrival at 2019/04/18 sanwa shop"
}
```
```json
{
"success": true,
"charge": {
"id": 1,
"amount": 7500,
"register_id": 1,
"created_at": "2019-04-17T21:50:49.000+09:00",
"updated_at": "2019-04-17T21:50:49.000+09:00"
}
}
```
|:---:|---|
|POST|`base_url/api/v1/deposits`|
|○|×|○|×|
* request body sample:
```json
{
"amount": 3000,
"detail": "okodukai from boss"
}
```
```json
{
"success": true,
"charge": {
"id": 2,
"amount": 7500,
"register_id": 1
}
}
```

add detail for auditlog

---

app/models/register.rb

fix aggregate method

---

db/migrate/20190411153042_create_register.rb
db/migrate/20190411161427_create_returns.rb
db/schema.rb

register/checkするとその後register/balancesしても500になるのを直した

fix register check

---

front/app/components/assets/MainAside.vue
front/app/layouts/default.vue

enabled to scroll when the sidebar exceeds the height of the display

---

.rubocop.yml
db/migrate/20190508214454_add_cost_to_create_purchase_items.rb
db/schema.rb

add rule and fix rule violations

---

app/controllers/api/products_controller.rb

remove comment-outed lines

---

app/controllers/api/products_controller.rb
app/controllers/api/purchases_controller.rb
app/controllers/api/users_controller.rb
app/models/purchase.rb
app/models/user.rb
config/routes.rb

`GET base_url/{entities}/actives` can get active entity records.
* purchases
* products
* users

add actives methods
